#!/usr/bin/env python3

###############################################################################
# Sunswift High Level build tool
# Version: V2.2
# Date: 7/01/2026
# Author: Ryan Wong (Updated)
#
# Wrapper around CMake to allow you to intuitively build, install, and test
# 
# Usage:
#   - srbuild all
#   - srbuild target node1 node2 ...
#   - srbuild clean
###############################################################################

import argparse
import subprocess
import time
import shutil
from typing import Optional
from pathlib import Path
from srutils import resolve_repo_root, validate_repo_root, die

CWD = Path.cwd().resolve()
REPO_ROOT = Path()
BUILD_DIR_PATH = Path()
CMAKELISTS_PATH = Path()
INSTALL_PREFIX = Path()

def safe_rmdir(path: Path) -> bool:
    if not path.exists():
        print("Clean: Path does not exist")
        return False
    if not path.is_dir() or path.is_symlink():
        print("Clean: Path is invalid for removal")
        return False
    try:
        path.relative_to(REPO_ROOT)
    except ValueError:
        print("Path not within repository space")
        return False
    
    if path == REPO_ROOT or path == "/" or path == REPO_ROOT / "src" or path == REPO_ROOT / "core":
        die("Operation denied: Safe guard triggered.")

    shutil.rmtree(path)
    return True

def configure_cmake() -> None:
    print("============ CMake Initialisation ============")
    if not (CMAKELISTS_PATH.exists() and CMAKELISTS_PATH.is_file()):
        die("Build: Root CMakeLists.txt does not exist")
    if not (BUILD_DIR_PATH.exists() and BUILD_DIR_PATH.is_dir()):
        print("Build: Root build directory not found, creating build/")
        try:
            BUILD_DIR_PATH.mkdir()
        except Exception as e:
            die(f"Error: Failed to create build directory: {e}")

    try:
        print("Build: Initialising CMake")
        subprocess.run([
            "cmake", "-S", str(REPO_ROOT), "-B", str(BUILD_DIR_PATH), f"-DCMAKE_INSTALL_PREFIX={INSTALL_PREFIX}"
        ], check=True)
    except subprocess.CalledProcessError as e:
        die(f"Build: Error configuring CMake: {e}")

def build(targets: Optional[list[str]], jobs: int) -> None:
    print("============= Building Targets ===============")
    jobs_str = f"{jobs}"
    start_time = time.time()
    try:
        if targets is None:
            print("Build: Building all targets")
            subprocess.run(["cmake", "--build", str(BUILD_DIR_PATH), "-j", jobs_str], check=True)
        else:
            print("Build: Building specified targets")
            for target in targets:
                subprocess.run(["cmake", "--build", str(BUILD_DIR_PATH), "--target", target, "-j", jobs_str], check=True)
    except subprocess.CalledProcessError:
        die("Build: Error building targets")
    
    print("=============== Build Complete =================")
    print(f"Build finished in {time.time()-start_time:.4f} seconds")

def install(targets: Optional[list[str]]) -> None:
    print("============= Installing Targets ===============")
    start_time = time.time()
    try:
        if targets is None:
            print("Install: Installing all targets")
            subprocess.run(["cmake", "--install", str(BUILD_DIR_PATH)], check=True)
        else:
            print("Install: Installing specified targets")
            for target in targets:
                subprocess.run(["cmake", "--install", str(BUILD_DIR_PATH), "--component", target], check=True)

        subprocess.run(["cmake", "--install", str(BUILD_DIR_PATH), "--component", "tools"], check=True)
    except subprocess.CalledProcessError:
        die("Build: Error installing targets")

    print("=============== Install Complete =================")
    print(f"Install finished in {time.time()-start_time:.4f} seconds")

def clean() -> None:
    print("============= Cleaning Targets ===============")
    res = input("Would you like to remove /build from repository root? (y/n): ")
    if res.lower() != "y":
        die("Cancelling clean..")

    build_path = REPO_ROOT / "build"
    if build_path.exists() and build_path.is_dir():
        print("Clean: Removing 'build' directory")
        if safe_rmdir(build_path): 
            print("Clean: 'build' removed successfully.")
    else:
        print(f"Clean: {build_path} does not exist")
    print("============== Clean Complete ================")

def main():
    parser = argparse.ArgumentParser(description="Sunswift build and staging tool")
    common_flags = argparse.ArgumentParser(add_help=False)
    common_flags.add_argument("--jobs", "-j", default=8, type=int, help="Parallel jobs. Default=8")
    
    level1_junction = parser.add_subparsers(dest="command", required=True)
    level1_junction.add_parser("all", parents=[common_flags], help="Build and install all targets")
    level1_junction.add_parser("clean", help="Delete the build directory")
    
    command_target = level1_junction.add_parser("target", parents=[common_flags], help="Select specific nodes to build")
    command_target.add_argument("targets", nargs="+", help="One or more target names")
    args = parser.parse_args() 

    global REPO_ROOT, BUILD_DIR_PATH, CMAKELISTS_PATH, INSTALL_PREFIX
    try:
        REPO_ROOT = resolve_repo_root(CWD)
        validate_repo_root(REPO_ROOT)
    except Exception as exc:
        die(str(exc))
        
    BUILD_DIR_PATH = REPO_ROOT / "build"
    CMAKELISTS_PATH = REPO_ROOT / "CMakeLists.txt"
    INSTALL_PREFIX = REPO_ROOT / "deploy"

    if args.command == "all":
        configure_cmake()
        build(None, args.jobs)
        install(None)
    elif args.command == "target":
        configure_cmake()
        build(args.targets, args.jobs)
        install(args.targets)
    elif args.command == "clean":
        clean()

if __name__ == "__main__":
    main()