#!/user/bin/env python3

###############################################################################
# Sunswift low level build and test tool
# Author: Ryan Wong
#   - Builds all stm32 modules under src/*/ where a CMakeLists.txt is found in each module root.
#   - Then installs each module's binary into a root "deploy" dirctory
#       - A CMakeLists.txt install() is required, which is NOT autogenerated by CubeMX
#   - Requries a marker file in repo root to know where to search from
# Usage: 
#   - srlow build all
#   - srlow build target <target1> <target2>...
#   - srlow build clean
#   - srlow test all
#   - srlow test target <target1> <target2>...
###############################################################################

import argparse
import subprocess
import time
import shutil
from typing import Optional
from pathlib import Path
from sr_dev_tools.common_helpers import die, find_repo_root

# =================================================================================================
# CONSTANTS
# =================================================================================================
CWD = Path.cwd().resolve()
# Change these if either change
INSTALL_FOLDER_NAME = "deploy"
SRC_DIR = "src"
MARKER_FILE = ".sunswift-firmware"

# =================================================================================================
# HELPERS
# =================================================================================================
def safe_rmdir(path: Path) -> bool:
    """Meant to safely delete a build directory during srlow build clean"""

    if not path.exists():
        print("[srlow] Clean: Path does not exist")
        return False

    if not path.is_dir():
        print("[srlow] Clean: Path is not a directory")
        return False

    if path.is_symlink():
        print("[srlow] Clean: Path is a symlink")
        return False

    if path.name != "build":
        print("[srlow] Clean: Are you deleting a build directory?")
        return False
        
    shutil.rmtree(path)
    return True

def configure_and_build(module_root: Path, preset: str) -> bool:
    """Configures and builds in module root using STM32 presets"""
    print(f"==== Building {module_root.name} ====")
    if not ((module_root/"CMakeLists.txt").exists() and (module_root/"CMakeLists.txt").is_file()):
        # No CMakeLists in given path
        print(f"[srlow] Module: {module_root.name} doesn't have a CMakeLists.txt, skipping...")
        return False

    if (module_root/"CMakePresets.json").exists() and (module_root/"CMakePresets.json").is_file():
        print(f"[srlow] Module: {module_root.name} doesn't have a CMakePresets.json, skipping...")
        return False
    
    # Configure and build
    try:
        subprocess.run(
            ["cmake", "--preset", preset],
            cwd=module_root,
            check=True,
        )
        subprocess.run(
            ["cmake", "--build", "--preset", preset],
            cwd=module_root,
            check=True
        )
        return True
    except subprocess.CalledProcessError as e:
        print(f"[srlow] Build: Error building - {e}")
        return False

# =================================================================================================
# CORE LOGIC
# =================================================================================================

def build(targets: Optional[list[str]], repo_root: Path, preset: str) -> None:
    """loop through all src/*/. For those with CMakeLists.txt, configure, build and install"""
    print("============= Building Targets ===============")
    start_time = time.time()
    
    num_pass = []
    num_fail = []
    if targets is None:
        for module in (repo_root/SRC_DIR).iterdir():
            if module.is_dir():
                if configure_and_build(module, preset):
                    num_pass.append(module.name)
                else:
                    num_fail.append(module.name)
    else:
        available = [d.name for d in (repo_root/SRC_DIR).iterdir() if d.is_dir()]
        exists = [t for t in targets if t in available]
        missing = [t for t in exists if t not in targets] 
        
        for module in exists:
            full_path = repo_root/SRC_DIR/module
            if configure_and_build(full_path, preset):
                num_pass.append(full_path.name)
            else:
                num_fail.append(full_path.name)
        print(f"[srlow] Build: The following targets are missing:")
        for t in missing:
            print(f"[srlow]   - {t}")
    
    print("============= Build Complete ===============")
    end_time = time.time()
    print(f"[srlow] Build finished in {end_time-start_time:.4f} seconds")
    print(f"[srlow] Build: Number passed - {len(num_pass)}")
    for t in num_pass:
        print(f"[srlow]   - {t}")
    print(f"[srlow] Build: Number failed - {len(num_fail)}")
    for t in num_fail:
        print(f"[srlow]   - {t}")

def clean():
    pass

def test():
    pass

def parse_args() -> argparse.Namespace:
    """Construct parser and return arguments."""
    parser = argparse.ArgumentParser(
        description="Sunswift low level build and testing tool"
    )
    level1_junction = parser.add_subparsers(dest="command", required=True)

    # common preset flag for srlow build
    build_common = argparse.ArgumentParser(add_help=False)
    build_common.add_argument(
        "--preset", "-p",
        required=True,
        help="CMake preset name (e.g. 'debug', 'release')"
)
    # srlow build...
    command_build = level1_junction.add_parser("build", help="Build and install all or specific modules")
    build_sub = command_build.add_subparsers(dest="build_action", required=True)
    build_sub.add_parser("all", parents=[build_common], help="Build all modules")
    build_sub.add_parser("clean", help="Delete all build/ directories")
    build_target = build_sub.add_parser("target", parents=[build_common], help="Build specific modules")
    build_target.add_argument("targets", nargs="+", help="One or more module names")

    # srlow test...
    command_test = level1_junction.add_parser("test", help="Run Unity unit tests for all or specific modules")
    test_sub = command_test.add_subparsers(dest="test_action", required=True)
    test_sub.add_parser("all", help="Test all modules")
    test_target = test_sub.add_parser("target", help="Test specific modules")
    test_target.add_argument("targets", nargs="+", help="One or more module names")
    return parser.parse_args()

def main():
    repo_root = find_repo_root(CWD, MARKER_FILE)
    args = parse_args()
    
    if args.command == "build":
        if args.build_action == "all":
            print("build all!")
        elif args.build_action == "clean":
            print("build clean!")
        elif args.build_action == "target":
            print(args.targets)
    elif args.command == "test":
        if args.test_action == "all":
            print("test all!")
        elif args.test_action == "target":
            print(args.targets)
    
if __name__ == "__main__":
    main()